global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: payment-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - payment-api-1:8080
          - payment-api-2:8080
        labels:
          service: payment-api

  - job_name: invoice-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - invoice-api-1:8080
          - invoice-api-2:8080
        labels:
          service: invoice-api
