server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: payment-api
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

app:
  instance-id: ${INSTANCE_ID:local}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      service: ${spring.application.name}
      instance: ${INSTANCE_ID:local}
